{include file="../layout/header.phtml"}
<script src="/public/js/jquery.js"></script>
<div class="normalheader transition animated fadeIn" style="margin-bottom:30px;">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="#">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>
            <h2 class="font-light m-b-xs">账户开户</h2>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 right animated-panel zoomIn" style="animation-delay: 0.1s;">
        <div style="text-align: right;margin-right: 40px;">
            <button class="btn w-xs btn-info " onclick="toList('{$id}')">子账户列表</button>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="col-lg-12 animated-panel bounceIn animate" style="animation-delay: 0.2s;">
            <div class="hpanel">
                <div class="panel-body form-horizontal">
                    <div class="form-group"><label class="col-sm-2 control-label">登录名：</label>
                        <div class="col-sm-6">
                            <input type="text" class="required pattern form-control m-b" style="width:230px;" placeholder="手机号" value="" required="required" name="userName" id="userName">
                        </div>
                    </div>
                    <div class="form-group"><label class="col-sm-2 control-label">密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>
                        <div class="col-sm-6">
                            <input type="text" class="required pattern form-control m-b" style="width:230px;" placeholder="密码" value="" required="required" name="passWord" id="passWord">
                        </div>
                    </div>
                    <div class="form-group"><label class="col-sm-2 control-label">备&nbsp;&nbsp;&nbsp;&nbsp;注：</label>
                        <div class="col-sm-6">
                            <input type="text" class="required pattern form-control m-b" style="width:230px;" placeholder="" value="" required="required" name="remark" id="remark">
                        </div>
                    </div>
                    <div class="col-sm-8 col-sm-offset-2">
                        <input type='hidden' name="id" id="id" value="{$id}">
                        <button class="btn btn-info" onclick="checkInfo()"> 保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{include file="../layout/footer.phtml"}
<script>
    function toList(id){
        location.href = "/Account/childlist?id="+id;
    }
    function checkInfo() {
        var id = $('#id').val();
        var regNum = /^[0-9]*[1-9][0-9]*$/;
        var userName = $.trim($('#userName').val());
        var passWord = $.trim($('#passWord').val());
        var remark = $.trim($('#remark').val());
        if (!id){
            alert("无效数据");
            return false;
        }
        if(!userName){
            alert("登录名不能为空");
            return false;
        }
        if(!regNum.test(userName)||userName.length !=11){
            alert("请输入有效的手机号");
            return false;
        }
        if(!passWord){
            alert("密码不能为空");
            return false;
        }
        if(passWord.length<6){
            alert("密码至少需要6位");
            return false;
        }else {
            $.ajax({
                url:'/Account/dochild',
                type:'post',
                async:false,
                data:'id='+id+'&userName='+userName+'&passWord='+passWord+'&remark='+remark,
                dataType:'json',
                success:function(data){
                    if(data.status=="success"){
                        alert(data.msg);
                        location.href = data.url;
                    }else{
                        alert(data.msg);
                        return false;
                    }
                }
            });
        }
    }
</script>