{include file="../layout/header.phtml"}
<script src="/public/js/choiceCategory.js"></script>
<div class="normalheader transition animated fadeIn" style="margin-bottom:10px;">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="#">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li>
                        <span>帐户列表</span>
                    </li></ol>
            </div>
            <h2 class="font-light m-b-xs">
                帐户列表            </h2>
            <small>帐户列表</small>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="col-lg-12 animated-panel bounceIn animate" style="animation-delay: 0.2s;">
            <div class="content" style="padding: 5px 40px 40px 10px">
                <form role="search" class="form-inline" method="get" action="/Account/list">
                    <input type="hidden" name="active_id" value="0">
                    <input type="hidden" name="tid" value="0">
                    <div class="form-group">
                        <label>用户名：</label>
                        <input type="text" name="useName" class="form-control" placeholder="用户名" value="{if isset($userName)}{$userName}{/if}">

                    </div>
                    <button type="submit" name="search" class="btn btn btn-primary ">筛选</button>
                </form>
                <div style="text-align: right;margin-right: -30px;">
                    {if $userId|getMatter:"Account":"create"==true}
                    <button class="btn w-xs btn-info " onclick="toCreate()">账户开户</button>
                    {/if}
                </div>
            </div>

            <div class="hpanel">

                <div class="panel-body">
                    <table class="table table-bordered">
                        <tr style="background: lavender;" >
                            <th>用户头像</th>
                            <th>用户名称</th>
                            <th>公司名称</th>
                            <th>开户银行</th>
                            <th>银行名称</th>
                            <th>银行帐户</th>
                            <th>充值余额(元)</th>
                            <th>帐户可用(元)</th>
                            <th>开户时间</th>
                            <th>操作</th>
                        </tr>
                        <tbody class="goods-body">
                        {foreach from=$lists item=info}
                        <tr class="tr-bd" >
                            <td>
                                <img src="{$info.headImg}"  class="img-rounded" width="60px;" height="60px;">
                            </td>
                            <td  title="{$info.userName}">{$info.userName}
                            </td>
                            <td >{$info.company}</td>
                            <td>{$bankList[$info.bank]}</td>
                            <td>{$info.bankName}</td>
                            <td>{$info.card}</td>
                            <td>{$info.money}</td>
                            <th>
                                {if isset($info.userId)}
                                    {$info.userId|getBalanceInfo}
                                {/if}
                            </th>
                            <td>
                                {if isset($info.createDate)}
                                    {$info.createDate}
                                {/if}
                            </td>
                            <td>
                                {if $userId|getMatter:"Account":"edit"==true}
                                <a href="/Account/edit?id={$info._id}">修改信息</a>&nbsp;
                                {/if}
                                {if $userId|getMatter:"Account":"addMoney"==true}
                                <a href="/Account/addMoney?id={$info._id}">充值</a>&nbsp;
                                {/if}
                                {if $userId|getMatter:"Account":"childlist"==true}
                                <a href="/Account/childlist?id={$info._id}">子账号管理</a>
                                {/if}
                                {if $userId|getMatter:"Account":"changePass"==true}
                                <a   data-target="#myModal8" onclick="changePassModel('{$info._id}','{$info.userName}')">重置密码</a>
                                {/if}
                            </td>
                        </tr>
                        {/foreach}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

        <div class="col-sm-8 pull-right pages">
            <span style="float:right">{$pages}</span>
        </div>
    </div>

</div>


<div class="modal fade hmodal-info " id="myModal8" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 class="modal-title">重置密码</h4>
            </div>
            <div class="modal-body">
                <form method="post" class="form-horizontal" id="pass">
                    <div class="form-group"><label class="col-sm-4 control-label">用户名</label>
                        <div class="col-sm-8" id="userName">

                        </div>
                        <input type="hidden" class="form-control" name="userName" value="">
                        <input type="hidden" class="form-control" name="id" value="">
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-4 control-label">新密码</label>
                        <div class="col-sm-8"><input type="password" class="form-control" name="password1"></div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-4 control-label">确认密码</label>
                        <div class="col-sm-8"><input type="password" class="form-control" name="password2"></div>
                    </div>
                    <div class="hr-line-dashed"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="chanagePass();">确认</button>
            </div>
        </div>
    </div>
</div>



{include file="../layout/footer.phtml"}
<script>
    function toCreate(){
        location.href = "/Account/create";
    }
    function changePassModel(id,userName){
        $('#userName').html(userName);
        $(':input[name="userName"]').val(userName);
        $(':input[name="id"]').val(id);
        $(':input[name="password1"]').val('');
        $(':input[name="password2"]').val('');
        $('#myModal8').modal();
    }
    function chanagePass(){
        var pass1 = $(':input[name="password1"]').val();
        var pass2 = $(':input[name="password2"]').val();
        if(pass1!=pass2){
            alert("新密码和确认密码不一致");
            return false;
        }
        if(pass1.length<6){
            alert("密码至少需要6位");
            return false;
        }
        var data = $('#pass').serialize();
        console.log('formData',data);
        $.ajax({
            url:'/Account/changePass',
            type:'post',
            data:data,
            dataType:'json',
            success:function(data){
                if(data.status == 'success'){
                    toastr.options = {
                        "positionClass": "toast-top-center",//弹出窗的位置
                    };
                    toastr.info('操作成功');
                    $('#myModal8').modal('hide');
                }else{
                    swal({
                        title: "操作失败",
                        text: "原因："+data.msg
                    });

                }
            },
            async:false
        });

    }
</script>