<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{$title}</title>
        <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <meta HTTP-EQUIV="Cache-Control" CONTENT="no-store">
        <meta HTTP-EQUIV="Expires" CONTENT="0">
        <link rel="stylesheet" href="/public/vendor/fontawesome/css/font-awesome.css"/>
        <link rel="stylesheet" href="/public/vendor/metisMenu/dist/metisMenu.css"/>
        <link rel="stylesheet" href="/public/vendor/animate.css/animate.css"/>
        <link rel="stylesheet" href="/public/vendor/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="/public/vendor/xeditable/bootstrap3-editable/css/bootstrap-editable.css"/>
        <link rel="stylesheet" href="/public/vendor/select2-3.5.2/select2.css"/>
        <link rel="stylesheet" href="/public/vendor/select2-bootstrap/select2-bootstrap.css"/>
        <link rel="stylesheet" href="/public/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css"/>
        <link rel="stylesheet" href="/public/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css"/>
        <link rel="stylesheet" href="/public/vendor/sweetalert/lib/sweet-alert.css"/>
        <link rel="stylesheet" href="/public/vendor/toastr/build/toastr.min.css"/>
        <link rel="stylesheet" href="/public/css/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css" />
        <!-- App styles -->
        <link rel="stylesheet" href="/public/css/bootstrap.css">
        <link rel="stylesheet" href="/public/css/style.css">
        <link rel="stylesheet" href="/public/css/page.css"/>
        <script src="/public/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/public/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="/public/vendor/jquery-ui/jquery-ui.min.js"></script>
        <script src="/public/vendor/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="/public/vendor/metisMenu/dist/metisMenu.min.js"></script>
        <script src="/public/vendor/iCheck/icheck.min.js"></script>
        <script src="/public/vendor/sparkline/index.js"></script>
        <script src="/public/vendor/moment/moment.js"></script>
        <script src="/public/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.js"></script>
        <script src="/public/vendor/xeditable/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
        <script src="/public/vendor/select2-3.5.2/select2.min.js"></script>
        <script src="/public/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
        <script src="/public/vendor/sweetalert/lib/sweet-alert.min.js"></script>
        <script src="/public/vendor/toastr/build/toastr.min.js"></script>
        <script src="/public/js/homer.js"></script>

    </head>
<body >


           

